Clarify timing support suggestion for a chain of mcontrol load triggers
riscv/riscv-debug-spec pull request #1023
Opened 2024-04-26 16:29 UTC by en-sc

Related to #1011

2024-04-26 17:23 UTC, rtwfroody requested changes

2024-04-26 17:23 UTC, rtwfroody commented on xml/hwbp_registers.xml
> +        address trigge if it can be chained with a load data trigger.
```suggestion
        &lt;&lt;tab:hwbp_timing&gt;&gt;, both timings should be supported on load
        address triggers that can be chained with a load data trigger.
```

2024-04-26 17:32 UTC, en-sc commented on xml/hwbp_registers.xml
> +        address trigge if it can be chained with a load data trigger.
Thanks for the catch! Addressed.

2024-04-26 22:14 UTC, pdonahue-ventana approved these changes
Sounds right to me.  If anybody asks: Any hardware that complied with the previous statement will also comply with the new statement, so there's no compatibility problem (and it's only a "should" anyway).

2024-05-15 16:30 UTC, rtwfroody approved these changes

2024-05-15 16:30 UTC, merged