Make data registers Message Registers.
riscv/riscv-debug-spec pull request #728
Opened 2022-05-12 16:41 UTC by timsifive

Message Registers allow data to be sent to the other side, but not to be
read back by the side that wrote the data.

This allows smaller FPGA implementations by duplicating the storage and
removing muxes in the design, addressing part of #717.

It is incompatible with old debuggers, if they use these registers in
surprising ways.

2022-05-12 19:09 UTC, pdonahue-ventana requested changes

2022-05-12 19:37 UTC, timsifive commented on debug_module.tex
> +\unspecified.  Thus the MR can be used to exchange data with the other side, but
Looks fine to me:
![image](https://user-images.githubusercontent.com/16123885/168154487-6d692261-3124-4c66-88f6-490723cfe1c9.png)

TeX macro names that are more than one character long can only contain upper and lowercase letters. (https://texfaq.org/FAQ-whatmacros) We have several \undefined\ in our code, and I think in every case the second \ is unnecessary.

2022-05-12 19:39 UTC, timsifive commented on debug_module.tex
> +    duplicated (one set of flip-flops for sending and one for receiving) to
"bits" instead of "flip-flops"? State seems a little too generic, and "set of state" doesn't sound right.

2022-05-12 20:23 UTC, pdonahue-ventana commented on debug_module.tex
> +\unspecified.  Thus the MR can be used to exchange data with the other side, but
OK.  I just wanted to make sure.

2022-05-12 20:24 UTC, pdonahue-ventana commented on debug_module.tex
> +    duplicated (one set of flip-flops for sending and one for receiving) to
"bits" sounds good.

2022-05-13 16:55 UTC, timsifive commented on debug_module.tex
> +    duplicated (one set of flip-flops for sending and one for receiving) to
Done.

2022-05-13 17:10 UTC, pdonahue-ventana approved these changes

2022-05-16 16:08 UTC, merged