Fix #817
riscv/riscv-debug-spec pull request #818
Opened 2023-03-07 00:15 UTC by pdonahue-ventana

2023-03-07 17:26 UTC, timsifive requested changes
Can you make the title descriptive?

2023-03-07 17:46 UTC, pdonahue-ventana commented
Done.

2023-03-07 17:57 UTC, timsifive approved these changes

2023-03-22 00:38 UTC, pdonahue-ventana commented
@timsifive can you merge this?  (I just always let you do the merge.)

2023-03-22 17:33 UTC, merged