Remove references to the timing bit.
riscv/riscv-debug-spec pull request #831
Opened 2023-04-01 00:52 UTC by pdonahue-ventana

Fixes #827.  Also changed trigger examples to fix some bugs, add the type field, add vs/vu in some examples, enhance one example to include textra, etc.

2023-04-03 17:43 UTC, timsifive requested changes

2023-04-03 23:58 UTC, pdonahue-ventana commented on debugger_implementation.tex
> +    \RcsrTdataOne & 0x68005159 & type=6, dmode=1, action=1, select=0, match=0, m=1, s=1, u=1, load=1 \\
Oh yeah.  I noticed that there was a bug in the original spec value but then I only partially fixed it.

2023-04-04 15:49 UTC, timsifive requested changes

2023-04-04 15:49 UTC, timsifive commented on debugger_implementation.tex
> +    \RcsrTdataTwo 1 & 0x03000000 & mhselect=6, mhvalue=0 \\
I don't see this addressed.

2023-04-04 15:49 UTC, timsifive commented on debugger_implementation.tex
> +    \RcsrTdataTwo 0 & 0x03000000 & mhselect=6, mhvalue=0 \\
This one either.

2023-04-04 16:23 UTC, pdonahue-ventana reviewed
I thought that I added all the changes to a batch and then committed that batch.  I guess not.  Unless I screwed something up again, they should all be there now.

2023-04-05 15:58 UTC, timsifive approved these changes

2023-04-06 16:40 UTC, merged